### ISSUE TITLE
extract() consumes FrontMatterExtractor

### ISSUE THREAD

**Issue by benwis** [khonsulabs/pulldown-cmark-frontmatter#2]
It looks like the intention with .extract() was to process an iterator to remove the frontmatter and return it, but the Parser iterator is consumed by FrontmatterExtractor::new() and FrontmatterExtractor is consumed by extract(), so functionally its impossible to do that

**Comment by ecton** [comment]
`FrontmatterExtractor` is itself [an iterator](https://docs.rs/pulldown-cmark-frontmatter/latest/pulldown_cmark_frontmatter/struct.FrontmatterExtractor.html#impl-Iterator-for-FrontmatterExtractor%3C'a,+T%3E). After grabbing the extracted frontmatter, the remaining tokens that were not part of the extracted frontmatter can be iterated over.

**Comment by benwis** [comment]
I don't think it's that easy, although I'd love it to be, I know it's an iterator. Take this code for example
```rust
pub fn process_stream_with_frontmatter<'a,T>(parser: FrontmatterExtractor<'a, T>, langs: &Lazy<Langs, fn() -> Langs>, toc: &mut Toc, output: &mut Vec<u8>, frontmatter_out: &mut Option<OwnedFrontmatter>)
    where T: Iterator<Item = Event<'a>>
{
    let mut current_code: Option<Code> = None;
    let mut current_heading: Option<Heading> = None;
    let mut in_blockquote = false;
    let mut in_figcaption = false;

    let frontmatter = parser.extract().unwrap();
    *frontmatter_out = Some(frontmatter.into());
    let stream = parser.map(|ev| {
// Do other parsing here
}

```
extract() moves and consumes the iterator `FrontmatterExtractor` and doesn't return it, so once extract is called, I lose access to the iterator. Am I missing something?

**Comment by ecton** [comment]
Oh, you're right, I hadn't looked at this library recently. `extract()` is purely provided to make it easier to extract the frontmatter if that's *all* you care about. This is the only way this function can work, because `FrontmatterExtracter` accepts an `Iterator<Item = Event<'a>>`, and there's no way to extract the information without advancing the underlying iterator.

If you want both the markdown events and the frontmatter, advance the `FrontmatterExtractor`'s iterator and then read the frontmater. This is how the [html example](https://github.com/khonsulabs/pulldown-cmark-frontmatter/blob/3f5ed8b7a1a21bc908c04f09817963eb577d46f0/examples/html.rs) works.

**Comment by benwis** [comment]
That could work, although that example looks like it runs through the whole iterator. I could match on ParsingState in the extractor to know when it's done finding frontmatter, but that's private, so I'd have to make a small change
